// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6qwMSbzACnbm4EtLveUMkQXQ1Jlp98I',
    appId: '1:361387580374:web:b3101d445342c5452b2277',
    messagingSenderId: '361387580374',
    projectId: 'homehero-app-223be',
    authDomain: 'homehero-app-223be.firebaseapp.com',
    storageBucket: 'homehero-app-223be.appspot.com',
    measurementId: 'G-46WWHQEN3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsqWDfu8-bdX-cdvo-fMCt9yUvx4qB35Q',
    appId: '1:361387580374:android:0402fc3bdab255152b2277',
    messagingSenderId: '361387580374',
    projectId: 'homehero-app-223be',
    storageBucket: 'homehero-app-223be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbLSxRU9jLMSw8INcw5PGTG1P906IkeRQ',
    appId: '1:361387580374:ios:a40b4cd1bcc31e092b2277',
    messagingSenderId: '361387580374',
    projectId: 'homehero-app-223be',
    storageBucket: 'homehero-app-223be.appspot.com',
    iosBundleId: 'com.example.homehero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbLSxRU9jLMSw8INcw5PGTG1P906IkeRQ',
    appId: '1:361387580374:ios:a40b4cd1bcc31e092b2277',
    messagingSenderId: '361387580374',
    projectId: 'homehero-app-223be',
    storageBucket: 'homehero-app-223be.appspot.com',
    iosBundleId: 'com.example.homehero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE6qwMSbzACnbm4EtLveUMkQXQ1Jlp98I',
    appId: '1:361387580374:web:bf394bf9d044778f2b2277',
    messagingSenderId: '361387580374',
    projectId: 'homehero-app-223be',
    authDomain: 'homehero-app-223be.firebaseapp.com',
    storageBucket: 'homehero-app-223be.appspot.com',
    measurementId: 'G-S90WWN5NV8',
  );
}
